"""baseline schema

Revision ID: 0c4d8b0dbbfa
Revises: 
Create Date: 2026-08-15 20:40:55.497825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4d8b0dbbfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_ats_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('work_authorization', sa.String(length=255), nullable=False),
    sa.Column('salary_expectation', sa.String(length=100), nullable=True),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('cv_filename', sa.String(length=255), nullable=True),
    sa.Column('cv_has_tables', sa.Boolean(), nullable=True),
    sa.Column('cv_has_multi_column', sa.Boolean(), nullable=True),
    sa.Column('cv_has_images', sa.Boolean(), nullable=True),
    sa.Column('cv_detected_sections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cv_text', sa.Text(), nullable=False),
    sa.Column('offer_text', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('structural_score', sa.Integer(), nullable=False),
    sa.Column('structural_issues', sa.JSON(), nullable=False),
    sa.Column('semantic_score', sa.Integer(), nullable=False),
    sa.Column('missing_keywords', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_search_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notified_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_url', sa.String(length=2048), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'offer_url', name='uq_notified_listing_user_offer_url')
    )
    op.create_table('personalization_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefilled_form_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('exclude_keywords', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_id', sa.Integer(), nullable=False),
    sa.Column('offer_url', sa.String(length=2048), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('ats_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'offer_url', name='uq_application_user_offer_url')
    )
    op.create_table('personalized_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnostic_id', 'kind', name='uq_personalized_document_diagnostic_kind')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personalized_documents')
    op.drop_table('applications')
    op.drop_table('saved_searches')
    op.drop_table('prefilled_form_request_logs')
    op.drop_table('personalization_request_logs')
    op.drop_table('notified_listings')
    op.drop_table('job_search_request_logs')
    op.drop_table('diagnostics')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('company_ats_mappings')
    # ### end Alembic commands ###
