"""add content_json and ats scores to personalized_documents

Revision ID: 5676911fe10a
Revises: d55174b608a5
Create Date: 2026-08-24 22:45:01.293927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5676911fe10a'
down_revision: Union[str, Sequence[str], None] = 'd55174b608a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalized_documents', sa.Column('content_json', sa.JSON(), nullable=True))
    op.add_column('personalized_documents', sa.Column('ats_score_before', sa.Integer(), nullable=True))
    op.add_column('personalized_documents', sa.Column('ats_score_after', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalized_documents', 'ats_score_after')
    op.drop_column('personalized_documents', 'ats_score_before')
    op.drop_column('personalized_documents', 'content_json')
    # ### end Alembic commands ###
