"""add onboarding profile fields

Revision ID: d3dd068cc26a
Revises: 0c4d8b0dbbfa
Create Date: 2026-08-24 12:19:49.090633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3dd068cc26a'
down_revision: Union[str, Sequence[str], None] = '0c4d8b0dbbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('desired_job_titles', sa.JSON(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('seniority_level', sa.String(length=50), nullable=True))
    op.add_column('candidate_profiles', sa.Column('desired_locations', sa.JSON(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('remote_preference', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('candidate_profiles', sa.Column('contract_types', sa.JSON(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('weekly_application_goal', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('profile_photo_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'profile_photo_key')
    op.drop_column('candidate_profiles', 'weekly_application_goal')
    op.drop_column('candidate_profiles', 'salary_max')
    op.drop_column('candidate_profiles', 'salary_min')
    op.drop_column('candidate_profiles', 'contract_types')
    op.drop_column('candidate_profiles', 'remote_preference')
    op.drop_column('candidate_profiles', 'desired_locations')
    op.drop_column('candidate_profiles', 'seniority_level')
    op.drop_column('candidate_profiles', 'desired_job_titles')
    # ### end Alembic commands ###
