"""add saved_job and diagnostic saved_job_id

Revision ID: d55174b608a5
Revises: 981bf5a6716c
Create Date: 2026-08-24 18:18:23.519622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55174b608a5'
down_revision: Union[str, Sequence[str], None] = '981bf5a6716c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ats_type', sa.String(length=50), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('full_offer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'offer_url')
    )
    op.add_column('diagnostics', sa.Column('saved_job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diagnostics', 'saved_jobs', ['saved_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagnostics', type_='foreignkey')
    op.drop_column('diagnostics', 'saved_job_id')
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
