"""add interview prep dossier, request log, company research cache

Revision ID: fe11059caac7
Revises: 5676911fe10a
Create Date: 2026-08-25 17:42:08.872487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe11059caac7'
down_revision: Union[str, Sequence[str], None] = '5676911fe10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_research_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('facts_json', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('interview_prep_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_prep_dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_job_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(length=50), nullable=False),
    sa.Column('extra_context', sa.Text(), nullable=True),
    sa.Column('web_search_used', sa.Boolean(), nullable=False),
    sa.Column('dossier_json', sa.JSON(), nullable=False),
    sa.Column('sources_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['saved_job_id'], ['saved_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_prep_dossiers')
    op.drop_table('interview_prep_request_logs')
    op.drop_table('company_research_caches')
    # ### end Alembic commands ###
